import { useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useGetTodosQuery, useAddTodoMutation, useAddUserMutation } from '@generated/graphql';

const Home: NextPage = () => {
  // query 実装
  const { loading: queryLoading, data: queryData, refetch } = useGetTodosQuery();

  // mutation 実装
  const [addTodo, { loading: userMutationLoading, error, data: userMutationData }] = useAddTodoMutation({
    onCompleted() {
      // mutation実行完了後、query再実行
      refetch();
    }
  });

  const [addUser] = useAddUserMutation();

  const [name, setName] = useState('');
  const [text, setText] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create GraphQL NextJS Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        GraphQL NextJS Project

        <form
          className={styles.form}
          onSubmit={e => {
            e.preventDefault();
            addUser({ variables: { name } });
            setName('');
          }}
        >
          <input value={name} onChange={e => setName(e.target.value)} />
          <button type="submit">createUser</button>
        </form>

        <br />

        <form
          className={styles.form}
          onSubmit={e => {
            e.preventDefault();
            addTodo({ variables: { text, userId: '1' } });
            setText('');
          }}
        >
          <input value={text} onChange={e => setText(e.target.value)} />
          <button type="submit">createTodo</button>
        </form>

        <br />

        {!queryLoading && queryData &&
          queryData.todos.map((todo) => (<li>{todo.text}</li>))
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
